//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMovie.Backend.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMovie.Backend.Common.ResourceVI", typeof(ResourceVI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản có độ dài &gt; 3 ký tự phải điền thông tin &lt;Tài khoản tổng hợp&gt;.
        /// </summary>
        public static string Account_LongerMinlength {
            get {
                return ResourceManager.GetString("Account_LongerMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cập nhật mật khẩu mới khi gọi vào DL.
        /// </summary>
        public static string ChangePass_Failed {
            get {
                return ResourceManager.GetString("ChangePass_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xóa bản ghi khi gọi vào DL.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi truy vấn Database.
        /// </summary>
        public static string Error_DatabaseQuery {
            get {
                return ResourceManager.GetString("Error_DatabaseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được hỗ trợ.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính khác.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp phải lớn hơn ngày sinh.
        /// </summary>
        public static string Identity_SmallerAge {
            get {
                return ResourceManager.GetString("Identity_SmallerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng chưa đủ tuổi để cấp chứng minh nhân dân.
        /// </summary>
        public static string Identity_Underage {
            get {
                return ResourceManager.GetString("Identity_Underage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh phải có trước ngày cấp.
        /// </summary>
        public static string Input_Date {
            get {
                return ResourceManager.GetString("Input_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thêm mới khi gọi vào DL.
        /// </summary>
        public static string InsertFaild {
            get {
                return ResourceManager.GetString("InsertFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không hợp lệ. Số tài khoản chi tiết phải bắt đầu bằng số của Tài khoản tổng hợp.
        /// </summary>
        public static string Invalid_AccountNumber {
            get {
                return ResourceManager.GetString("Invalid_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string Invalid_InputData {
            get {
                return ResourceManager.GetString("Invalid_InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên đăng nhập hoặc mật khẩu.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư nợ.
        /// </summary>
        public static string Nature_Debt {
            get {
                return ResourceManager.GetString("Nature_Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư có.
        /// </summary>
        public static string Nature_ExcessYes {
            get {
                return ResourceManager.GetString("Nature_ExcessYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưỡng tính.
        /// </summary>
        public static string Nature_Hermaphrodite {
            get {
                return ResourceManager.GetString("Nature_Hermaphrodite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có số dư.
        /// </summary>
        public static string Nature_NoBalance {
            get {
                return ResourceManager.GetString("Nature_NoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không chính xác.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH {0}.
        /// </summary>
        public static string Title_Content_Excel {
            get {
                return ResourceManager.GetString("Title_Content_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cập nhật khi gọi vào DL.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;{1}&gt; đã tồn tại. Xin vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Validate_DateOfBirth {
            get {
                return ResourceManager.GetString("Validate_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải xóa tất cả các tài khoản con trước khi xóa tài khoản cha.
        /// </summary>
        public static string Validate_DeleteRootId {
            get {
                return ResourceManager.GetString("Validate_DeleteRootId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không hợp lệ.
        /// </summary>
        public static string Validate_Email {
            get {
                return ResourceManager.GetString("Validate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mã nhân viên không hợp lệ.
        /// </summary>
        public static string Validate_EmployeeCodeFalse {
            get {
                return ResourceManager.GetString("Validate_EmployeeCodeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên  không được phép để trống.
        /// </summary>
        public static string Validate_EmployeeCodeNull {
            get {
                return ResourceManager.GetString("Validate_EmployeeCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được phép để trống.
        /// </summary>
        public static string Validate_FullNameNull {
            get {
                return ResourceManager.GetString("Validate_FullNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị giới tính không hợp lệ.
        /// </summary>
        public static string Validate_Gender {
            get {
                return ResourceManager.GetString("Validate_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Validate_IdentityDate {
            get {
                return ResourceManager.GetString("Validate_IdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Không được để trống.
        /// </summary>
        public static string Validate_InputNull {
            get {
                return ResourceManager.GetString("Validate_InputNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định không đúng định dạng.
        /// </summary>
        public static string Validate_LandlinePhone {
            get {
                return ResourceManager.GetString("Validate_LandlinePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động không đúng định dạng.
        /// </summary>
        public static string Validate_MobilePhone {
            get {
                return ResourceManager.GetString("Validate_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có độ dài &gt;= {1} ký tự.
        /// </summary>
        public static string ValueMinlength_Input {
            get {
                return ResourceManager.GetString("ValueMinlength_Input", resourceCulture);
            }
        }
    }
}
